[project]
name = "evergrain"
version = "0.7.0"
description = "Intelligent photo scanning and organization with automated cropping, enhancement, metadata embedding, and file renaming."
readme = "README.md"
authors = [
    { name = "Bryan Barcelona", email = "131413239+bryanbarcelona@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.0",
    "opencv-python>=4.11.0.86",
    "pillow>=12.0.0",
    "psutil>=7.2.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.pytest]
testpaths = ["tests"]
addopts = ["-v", "--tb=short"]

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[tool.ty.src]
include = ["src/", "tests/"]
exclude = [".venv/"]

[tool.ty.rules]
invalid-return-type = "error"

[tool.ruff]
preview = true
line-length = 120
target-version = "py312"
extend-exclude = ["tests", "legacy", "main.py"]
fix = true

lint.select = [
  "E", "W", "F", "I", "UP", "B", "C4", "S", "BLE", "FBT",
  "A", "C90", "T10", "ISC", "ICN", "G", "PIE", "T20",
  "PT", "Q", "RUF", "SIM", "TID", "ARG", "PTH", "ERA",
  "PL", "TRY", "ANN",  #  keep ANN, drop TCH/PYI
]
lint.ignore = [
  "E501", "ISC001", "COM812", "S101",
  "PLR0913", "PLR2004", "TRY003", "ANN401",
  "Q000", "Q003", "T201", "RUF003", "FBT001",
  "RUF067", "PLW0603", "ANN204",
]

#[tool.ruff.lint.per-file-ignores]
# Don't force strict typing or docstrings in test files
#"tests/*" = ["ANN001", "ANN201", "S101"]
#"enhancements.py" =  ["ANN001", "ANN201", "S101"]

[tool.ruff.lint.isort]
known-first-party = ["evergrain"]
combine-as-imports = true
force-wrap-aliases = true

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true

[tool.pip-audit]
exclude = ["brybox"]

[tool.commitizen]
version_provider = "uv"
tag_format = "v${version}"
major_version_zero = true
bump_message = "chore(release): $current_version → $new_version"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
publish-url = "https://upload.pypi.org/legacy/"
explicit = true

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true